name: nav_aif_fyp
description: A Flutter app for AI-based indoor navigation
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_tts: ^4.0.0
  permission_handler: ^12.0.1
  android_intent_plus: ^6.0.0
  speech_to_text: ^7.0.0
  cupertino_icons: ^1.0.2
  path_drawing: ^1.0.1
  google_fonts: ^6.0.0
  shared_preferences: ^2.2.2
  camera: ^0.11.0+1
  google_mlkit_object_detection: ^0.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/langs/